# Generated by Django 3.2.23 on 2023-11-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone_numbetr',
            new_name='phone_number',
        ),
    ]
